TestDjango/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('inicio.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('articulos/',include('articulos.urls')),
    path('cuentas/',include('cuentas.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articulos/urls.py
from django.urls import path
from .views import producto_lista, producto_nuevo, producto_editar, producto_borrar,producto_detalle,generarBoleta ,tienda,ver_carrito 
from . import views 

urlpatterns = [
    path('tienda/', tienda, name='tienda'),  # Lista de productos
    path('productos/nuevo', producto_nuevo, name='producto_nuevo'),  # Crear nuevo producto
    path('productos/editar/<int:id>/', producto_editar, name='producto_editar'),  # Editar producto
    path('productos/borrar/<int:pk>/', views.producto_borrar, name='producto_borrar'),  # Borrar producto
    path('productos/detalle/<int:id>/',producto_detalle, name='producto_detalle'),
    path('carrito/', ver_carrito, name='carrito'),
    path('limpiar/', views.limpiar_carrito, name='limpiar'),
    path('generarBoleta/', views.generarBoleta, name='generarBoleta'),
    path('agregar_producto/<id>/', views.agregar_producto, name='agregar_producto'),
    path('restar_producto/<id>/', views.restar_del_carrito, name='restar_producto'),
    path('productos/', producto_lista, name='lista_productos'),
    
    
]

inicio/urls.py
from django.urls import path
from .views import vistaIndex,vistaNosotros

urlpatterns=[
    path('',vistaIndex,name="Inicio"),
    path('nosotros/',vistaNosotros,name="Nosotros"),
    
]

articulos/models.py
from django.db import models
from distutils.command.upload import upload
from django.contrib.auth.models import User


class Marca(models.Model):
    idMarca = models.AutoField(primary_key=True, verbose_name="Id de Marca")
    nombreMarca=models.CharField(max_length=50, blank=True, verbose_name="Nombre Marca")

    def __str__(self):
        return self.nombreMarca


class Producto(models.Model):
    productoId = models.AutoField(primary_key=True, verbose_name="Id Producto")
    nombre = models.CharField(max_length=50, verbose_name="Nombre")
    imagen = models.ImageField(upload_to="imagenes", null=True, blank=True, verbose_name="Imagen")
    precio = models.IntegerField(blank=True, null=True, verbose_name="Precio")
    nombreMarca = models.ForeignKey(Marca, on_delete=models.CASCADE, verbose_name="Marca")
    stock = models.PositiveIntegerField(verbose_name="Stock",default=0)

    def __str__(self):
        return self.nombre
    
    
class Boleta(models.Model):
    id_boleta = models.AutoField(primary_key=True, verbose_name="Id Boleta")
    fecha = models.DateTimeField(auto_now_add=True , verbose_name="Fecha")
    total = models.BigIntegerField( verbose_name="Total")
    
    def __str__(self):
        return str(self.id_boleta)

class DetalleBoleta(models.Model):
    id_boleta = models.ForeignKey(Boleta,blank= True, on_delete=models.CASCADE)
    id_detalle_boleta = models.AutoField(primary_key=True)
    id_producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.IntegerField()
    subtotal = models.BigIntegerField()

    def __str__(self):
        return str(self.id_detalle_boleta)
    


# Create your models here.

articulos/forms.py
# forms.py
from django import forms
from django.forms import widgets
from .models import Producto

class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ['nombre', 'imagen', 'precio', 'nombreMarca','stock']  # No incluimos 'productoId'
        labels = {
            'nombre': 'Nombre Producto',
            'imagen': 'Imagen del producto',
            'precio': 'Precio del producto',
            'nombreMarca': 'Marca del producto',
            'stock': 'Stock del producto'
        }
        widgets = {
            'nombre': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Ingrese el nombre del producto',
                'id': 'nombre'
            }),
            'precio': forms.NumberInput(attrs={
                'class': 'form-control',
                'placeholder': 'Ingrese el precio del producto',
                'id': 'precio'
            }),
            'imagen': forms.FileInput(attrs={
                'class': 'form-control',
                'id': 'imagen'
            }),
            'nombreMarca': forms.Select(attrs={
                'class': 'form-control',
                'id': 'nombreMarca'
            }),
            'stock': forms.NumberInput(attrs={
                'class': 'form-control',
                'placeholder': 'Ingrese el stock del producto',
                'id': 'stock'
            })
        }

articulos/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, JsonResponse
from django.http import HttpResponseForbidden
from .models import Producto, Marca, Boleta,DetalleBoleta
from .forms import  ProductoForm
from django.contrib.auth.decorators import login_required
from .carrito import Carrito
from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test
from django.utils import timezone
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.

def admin_required(login_url=None):
    return user_passes_test(lambda u: u.is_active and u.is_staff, login_url=login_url)

def crear(request):
    return render(request,'crud/crear.html')

def producto_detalle(request, id):
    producto = get_object_or_404(Producto, productoId=id)
    context = {
        'productos': [producto]
    }
    return render(request, 'crud/detalle.html', context)

# CRUD para producto 

@admin_required()
def producto_lista(request):
    productos = Producto.objects.all()
    context={

        'productos':productos
    }
    return render(request, 'crud/Lista_productos.html',context)


def producto_nuevo(request):
    if request.method == "POST":
        form = ProductoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('lista_productos')
    else:
        form = ProductoForm()
    return render(request, 'crud/crear.html', {'form': form})
    
def producto_editar(request, id):
    producto = get_object_or_404(Producto, productoId=id)

    if request.method == 'POST':
        form = ProductoForm(request.POST, request.FILES, instance=producto)
        if form.is_valid():
            form.save()
            return redirect('lista_productos')  # Redirige a la página principal o lista de productos
    else:
        form = ProductoForm(instance=producto)

    context = {
        'form': form
    }
    return render(request, 'crud/modificar.html', context)



def producto_borrar(request, pk):
    producto = get_object_or_404(Producto, productoId=pk)
    producto.delete()
    return redirect('Inicio') 

@login_required
def tienda(request):
    productos_list = Producto.objects.all()
    paginator = Paginator(productos_list, 12) 
    page = request.GET.get('page')

    try:
        productos = paginator.page(page)
    except PageNotAnInteger:
        productos = paginator.page(1)
    except EmptyPage:
        productos = paginator.page(paginator.num_pages)

    return render(request, 'vista_usuario/tienda.html', {'productos': productos})


def agregar_producto(request, id):
    carrito = Carrito(request)
    producto = get_object_or_404(Producto, pk=id)
    carrito.agregar(producto=producto)
    return redirect('carrito')

def eliminar_del_carrito(request, producto_id):
    producto = get_object_or_404(Producto, productoId=producto_id)
    carrito = Carrito(request)
    carrito.eliminar(producto)
    return redirect('carrito')

def restar_del_carrito(request, id):
    carrito = Carrito(request)
    producto = Producto.objects.get(productoId=id)
    carrito.restar(producto = producto)
    return redirect('carrito')

def limpiar_carrito(request):
    carrito = Carrito(request)
    carrito.limpiar()
    return redirect('carrito')


def ver_carrito(request):
    carrito = Carrito(request)
    return render(request, 'vista_usuario/tienda.html', {'productos': Producto.objects.all()})  # Asegura que se renderice toda la tienda con el carrito


def generarBoleta(request):
    carrito = request.session.get('carrito', None)
    if not carrito:
        # Redirigir a una página de error o mostrar un mensaje
        return render(request, 'carrito/detallecarrito.html', {'error': 'El carrito está vacío.'})

    precio_total = 0
    detalles_boleta = []

    for key, value in carrito.items():
        precio_total += int(value['precio']) * int(value['cantidad'])

    # Crear la boleta
    boleta = Boleta(total=precio_total)
    boleta.save()

    # Crear los detalles de la boleta
    for key, value in carrito.items():
        producto = Producto.objects.get(productoId=value['productoId'])
        cant = value['cantidad']
        subtotal = cant * int(value['precio'])
        detalle = DetalleBoleta(id_boleta=boleta, id_producto=producto, cantidad=cant, subtotal=subtotal)
        detalle.save()
        detalles_boleta.append(detalle)

    datos = {
        'productos': detalles_boleta,
        'fecha': boleta.fecha,
        'total': boleta.total,
        'id_boleta': boleta.id_boleta,
    }

    request.session['boleta'] = boleta.id_boleta

    # Vaciar el carrito
    carrito = Carrito(request)
    carrito.vaciar()

    return render(request, 'carrito/detallecarrito.html', datos)

articulos/templates/crud/Lista_productos.html
{% extends 'base.html' %}

{% block contenido %}
{% load static %}
<div class="container mt-4">
    <h2>Listado de productos:</h2>
</div>
<div class="container">
    <div class="row">
        <div class="col-12">
            <table class="table table-striped table-hover table-bordered">
                <thead class="thead-dark">
                    <tr>
                        <th>ID</th>
                        <th>Nombre</th>
                        <th>Imagen</th>
                        <th>Precio</th>
                        <th>Marca</th>
                        <th>Stock</th>
                        <th>Ver Detalle</th>
                        <th>Editar</th>
                        <th>Eliminar</th>
                    </tr>
                </thead>
                <tbody>
                    {% for producto in productos %}
                    <tr>
                        <td style="padding: 20px;" scope="row">{{ producto.productoId }}</td>
                        <td style="padding: 20px;" scope="row">{{ producto.nombre }}</td>
                        <td style="padding: 20px;" scope="row">
                            <a><img src="{{ producto.imagen.url }}" class="img-fluid" style="max-width: 200px; max-height: 200px;"></a>
                        </td>
                        <td style="padding: 20px;" scope="row">{{ producto.precio }}</td>
                        <td style="padding: 20px;" scope="row">{{ producto.nombreMarca }}</td>
                        <td style="padding: 20px;" scope="row">{{ producto.stock }}</td>
                        <td style="padding: 20px;" scope="row">
                            <a href="{% url 'producto_detalle' id=producto.productoId %}" class="btn btn-sm btn-primary">Ver</a>
                        </td>
                        <td style="padding: 20px;" scope="row">
                            <a href="{% url 'producto_editar' id=producto.productoId %}" class="btn btn-sm btn-warning">Editar</a>
                        </td>
                        <td style="padding: 20px;" scope="row">
                            <a href="{% url 'producto_borrar' pk=producto.productoId %}" class="btn btn-sm btn-danger">Eliminar</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <div class="text-right mt-3">
                <a class="btn btn-primary" href="{% url 'producto_nuevo' %}">Crear producto</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

articulos/templates/crud/crear.html
<!-- crud/crear_producto.html -->
{% extends 'base.html' %}

{% block contenido %}
{% load static %}

<div class="container">
    <h2>Creando Artículo</h2>
    <form method="POST" id="formulario" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_nombre">{{ form.nombre.label }}</label>
            {{ form.nombre }}
            {% if form.nombre.errors %}
                <p class="text-danger">{{ form.nombre.errors }}</p>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="id_imagen">{{ form.imagen.label }}</label>
            {{ form.imagen }}
            {% if form.imagen.errors %}
                <p class="text-danger">{{ form.imagen.errors }}</p>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="id_precio">{{ form.precio.label }}</label>
            {{ form.precio }}
            {% if form.precio.errors %}
                <p class="text-danger">{{ form.precio.errors }}</p>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="id_nombreMarca">{{ form.nombreMarca.label }}</label>
            {{ form.nombreMarca }}
            {% if form.nombreMarca.errors %}
                <p class="text-danger">{{ form.nombreMarca.errors }}</p>
            {% endif %}
        </div>
        <div class="form-group">
            <label for="id_stock">{{form.stock.label}}</label>
            {{form.stock}}
            {% if form.stock.errors %}
                <p class="text-danger">{{form.stock.errors}}</p>
            {% endif %}
        </div>

        <br>
        <input type="submit" class="btn btn-primary" value="Enviar">
        <a href="{% url 'lista_productos' %}" class="btn btn-success">Volver</a>
    </form>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js"></script>
<script>
    $(document).ready(function(){
        $("#formulario").validate({
            rules: {
                nombre: "required",
                imagen: "required",
                precio: "required",
                nombreMarca: "required"
            },
            messages: {
                nombre: {
                    required: 'Ingrese un nombre.'
                },
                imagen: {
                    required: 'Ingrese una imagen.'
                },
                precio: {
                    required: 'Ingrese un precio.'
                },
                nombreMarca: {
                    required: 'Ingrese una marca.'
                }
            }
        });
    });
</script>
{% endblock %}

articulos/templates/crud/detalle.html
{% extends 'base.html' %}

{% block contenido %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mostrar Producto</title>
</head>
<body>
    <h2 style="text-align: center;"> Detalles del Producto </h2>
    <div style="display: flex;  "  class="container">

        <div class="row">
            {% for producto in productos %}
            
                <div class="col-8 col-md-4">
                    <div class="card text-center">
                        {% if producto.imagen %}
                            <img src="{{ producto.imagen.url }}" class="card-img-top mx-auto">
                        {% else %}
                            <img src="{% static 'img/sinfoto.webp' %}" class="card-img-top mx-auto">
                        {% endif %}
                        <div class="card-body">
                            <h4 class="card-title">Producto ID: {{ producto.productoId }}</h4>
                            <p class="card-text">
                                Marca: {{ producto.nombreMarca.nombreMarca }}<br>
                                Producto: {{ producto.nombre }}<br>
                                Precio: ${{ producto.precio }}<br>
                                Stock: {{ producto.stock }}<br>
                            </p>
                            <a href="{% url 'lista_productos' %}" class="btn btn-success">Volver</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</body>
</html>

{% endblock %}

articulos/templates/crud/eliminar.html
{%extends 'base.html'%}

{%block contenido%}
{%load static%}



{%endblock%}

articulos/templates/crud/modificar.html
{% extends 'base.html' %}

{% block contenido %}
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Modificar Producto</title>
    <!-- Cargar jQuery (necesario para el script de validación) -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js"></script>

    <style>
        .error {
            color: red;
        }
    </style>
    <script>
        $(document).ready(function(){
            $("#formulario").validate({
                rules: {
                    nombre: "required",
                    imagen: "required",
                    precio: "required",
                    nombreMarca: "required"
                },
                messages: {
                    nombre: {
                        required: 'Ingrese un nombre.'
                    },
                    imagen: {
                        required: 'Ingrese una imagen.'
                    },
                    precio: {
                        required: 'Ingrese un precio.'
                    },
                    nombreMarca: {
                        required: 'Ingrese una marca.'
                    }
                }
            });
        });
    </script>
</head>
<body>
    <div class="container">
        <h2>Modificar Producto</h2>
        <form method="POST" id="formulario" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <br><br>
            <input type="submit" class="btn btn-primary" value="Modificar">
            <a href="{% url 'lista_productos' %}" class="btn btn-success">Volver</a> <!-- Asegúrate de que 'index' es el nombre correcto -->
        </form>
    </div>
</body>
</html>

{% endblock %}